export const ScreenName = {
  STACK_LOGIN_SCREEN: 'StackLoginScreen',
  REGISTER_SCREEN: 'RegisterScreen',
  LOGIN_SCREEN: 'LoginScreen',
  FORGOT_PASSWORD: 'forgotScreen',
  HOME_BAR_STACK_SCREEN: 'HomeBarStackScreen',
  ONBOARD_SCREEN: 'onboardScreen',
  HOME_SCREEN: 'HomeScreen',
  SHOP_SCREEN: 'ShopScreen',
  FAVORITE_SCREEN: 'FavoriteScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  FILTER_SCREEN: 'FilterScreen',
  HOME_STACK_SCREEN: 'HomeStackScreen',
  SEARCH_SCREEN: 'SearchScreen',
  SEARCH_STACK_SCREEN: 'SearchStackScreen',
};
